# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: ãƒ¡ãƒ¢æŸ
email: itr.tert+code(@)gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  -
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
baseurl: "/note" # the subpath of your site, e.g. /blog
url: "https://itr-tert.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  itr-tert

permalink: /:year-:month-:day-:title:output_ext
# permalink: /:categories/:year/:month/:day/:title:output_ext


# Build settings
# bundle info --path minima
theme: minima
highlighter: rouge

minima:
  date_format: "%Y-%m-%d"


plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-toc
  - asciidoctor

destination: ./docs

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - build.sh
  - preview.sh
  - update.sh
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/


kramdown:
  hard_wrap: true  # æ”¹è¡Œã‚’æ”¹è¡Œã¨ã—ã¦æ‰±ã†

asciidoc:
  processor:                   asciidoctor
  require_front_matter_header: true
  ext:                         adoc

asciidoctor:
  safe:                        unsafe
  template_dir:                _templates
  experimental: true
  attributes:
    experimental: true
    source-highlighter: pygments
    hardbreaks:   true
    pygments-css: style
    # gems/gems/asciidoctor-2.0.18/data/locale/attributes-ja.adoc
    # Japanese translation, courtesy of Takayuki Konishi <seannos.takayuki@gmail.com>
    appendix-caption: ä»˜éŒ²
    appendix-refsig: {appendix-caption}
    # :chapter-signifier: ???
    # :chapter-refsig: {chapter-signifier}
    figure-caption: å›³
    last-update-label: æœ€çµ‚æ›´æ–°
    ifdef::listing-caption[:listing-caption: ãƒªã‚¹ãƒˆ]
    ifdef::manname-title[:manname-title: åå‰]
    # :part-signifier: ???
    # :part-refsig: {part-signifier}
    ifdef::preface-title[:preface-title: ã¾ãˆãŒã]
    # :section-refsig: ???
    table-caption: è¡¨
    toc-title: ç›®æ¬¡
    untitled-label: ç„¡é¡Œ
    version-label: ãƒãƒ¼ã‚¸ãƒ§ãƒ³
    # âš â˜…ğŸ’¬ğŸ“
    warning-caption:   "!!"
    caution-caption:   "ï¼"
    important-caption: "â˜…"
    note-caption:      "ï¼Š"
    example-caption:   "â›¤"
    tip-caption:       "ğŸ—¨ï¸"




toc:
    min_level: 1
    max_level: 2

#   ordered_list: false
#   no_toc_section_class: no_toc_section
#   list_id: toc
#   list_class: section-nav
#   sublist_class: ''
#   item_class: toc-entry
#   item_prefix: toc-
